[supervisord]
nodaemon=true

[program:cron]
command = /bin/bash -c "declare -p | grep -Ev '^declare -[[:alpha:]]*r' > /run/supervisord.env && /usr/sbin/cron -f -L 15"
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes=0
user = root
autostart = true
autorestart = true

[program:run-server]
command = /bin/bash /usr/src/app/run-server.sh 8282
user = progeo
redirect_stderr = true
stdout_logfile = /var/log/progeo.log
