# Generated by Django 6.0.3 on 2026-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeodevice',
            name='chip_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progeodevice',
            name='device_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progeodevice',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progeodevice',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
