# Generated by Django 6.0.3 on 2026-05-20 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeo.account'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='limitedtoken',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeo.account'),
        ),
        migrations.AlterField(
            model_name='limitedtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mfslog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeo.account'),
        ),
        migrations.AlterField(
            model_name='mfslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progeoalarm',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='progeo.progeomeasurement'),
        ),
        migrations.AlterField(
            model_name='progeodevice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progeo.progeolocation'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progeo.account'),
        ),
        migrations.AlterField(
            model_name='progeomeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progeo.progeodevice'),
        ),
        migrations.AlterField(
            model_name='progeomeasurepoint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='progeo.progeodevice'),
        ),
    ]
