# Generated by Django 6.0.5 on 2026-06-19 06:01

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0002_alter_backup_account_alter_backup_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeomeasurement',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='samples',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
