# Generated by Django 6.0.3 on 2026-05-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0002_progeodevice_chip_id_progeodevice_device_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progeodevice',
            old_name='device_hash',
            new_name='device_ip',
        ),
    ]
