# Generated by Django 6.0.3 on 2026-05-12 14:30

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0003_rename_device_hash_progeodevice_device_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeodevice',
            name='pull_resistance',
            field=models.IntegerField(choices=[(136, 'Default 100K'), (72, 'Res 10K'), (40, 'Res 1K'), (24, 'Res 100'), (8, 'Off')], default=136),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_threshold',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.CreateModel(
            name='ProgeoAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('triggered', models.BooleanField(default=False)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alarms', to='progeo.progeomeasurement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgeoMeasurePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('sensor_order', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='progeo.progeodevice')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
