# Generated by Django 6.0.5 on 2026-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0003_progeomeasurement_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeomeasurement',
            name='is_watching',
            field=models.BooleanField(default=False),
        ),
    ]
