# Generated by Django 6.0.5 on 2026-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0004_progeomeasurement_is_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeomeasurement',
            name='resistance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
