# Generated by Django 6.0.5 on 2026-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0004_progeomeasurement_is_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeodevice',
            name='type',
            field=models.CharField(blank=True, choices=[('imei', 'imei'), ('smartbox', 'smartbox'), ('node', 'node'), ('legacy', 'legacy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='resistance_idc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='resistance_vdc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
