# Generated by Django 6.0.3 on 2026-05-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0004_progeodevice_pull_resistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeomeasurepoint',
            name='last_value',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progeomeasurepoint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='progeo.progeodevice'),
        ),
    ]
