# Generated by Django 6.0.5 on 2026-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0005_progeomeasurement_resistance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progeomeasurement',
            old_name='resistance',
            new_name='resistance_idc',
        ),
        migrations.AddField(
            model_name='progeomeasurement',
            name='resistance_vdc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
