# Generated by Django 6.0.5 on 2026-07-04 14:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('progeo', '0005_progeodevice_type_progeomeasurement_resistance_idc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermissions',
            fields=[
            ],
            options={
                'permissions': (('module_navbar_enabled', 'Can access navbar module'), ('module_devices_enabled', 'Can access devices module'), ('module_devices_edit', 'Can edit devices module'), ('module_devices_delete', 'Can delete devices module'), ('module_measurements_enabled', 'Can access measurements module'), ('module_imei_enabled', 'Can access IMEI module'), ('module_backup_enabled', 'Can access backup module'), ('module_backup_delete', 'Can delete backup module'), ('module_docker_enabled', 'Can access Docker module'), ('module_admin_enabled', 'Can access admin module'), ('module_testsuite_enabled', 'Can access testsuite module'), ('module_profile_mail_edit', 'Can edit profile mail module')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='progeodevice',
            name='type',
            field=models.CharField(blank=True, choices=[('imei', 'imei'), ('smartbox', 'smartbox'), ('node', 'node'), ('relay', 'relay'), ('root', 'root'), ('legacy', 'legacy')], max_length=20, null=True),
        ),
    ]
