# Generated by Django 6.0.5 on 2026-08-13 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0007_progeolocation_city_progeolocation_mail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodulepermissions',
            options={'permissions': (('module_navbar_enabled', 'Can access navbar module'), ('module_locations_enabled', 'Can access locations module'), ('module_locations_edit', 'Can edit locations module'), ('module_locations_delete', 'Can delete locations module'), ('module_devices_enabled', 'Can access devices module'), ('module_devices_edit', 'Can edit devices module'), ('module_devices_delete', 'Can delete devices module'), ('module_measurements_enabled', 'Can access measurements module'), ('module_imei_enabled', 'Can access IMEI module'), ('module_backup_enabled', 'Can access backup module'), ('module_backup_delete', 'Can delete backup module'), ('module_docker_enabled', 'Can access Docker module'), ('module_admin_enabled', 'Can access admin module'), ('module_testsuite_enabled', 'Can access testsuite module'), ('module_profile_mail_edit', 'Can edit profile mail module'))},
        ),
        migrations.RemoveField(
            model_name='progeoalarm',
            name='triggered',
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='status',
            field=models.IntegerField(choices=[(0, 'neu'), (1, 'quittiert'), (2, 'stoerung')], default=0),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='lageplan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='media/uploads'),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='offset_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='offset_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='offset_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='offset_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
