# Generated by Django 6.0.5 on 2026-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0008_alter_usermodulepermissions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeoalarm',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='still_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
