# Generated by Django 6.0.5 on 2026-08-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0009_progeoalarm_sensor_id_progeoalarm_still_active_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progeomeasurepoint',
            name='device',
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='scale_x',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='scale_y',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='progeomeasurepoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='progeo.progeolocation'),
        ),
        migrations.AddField(
            model_name='progeomeasurepoint',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
