# Generated by Django 6.0.5 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0010_remove_progeomeasurepoint_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolocation',
            name='flip_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='flip_y',
            field=models.BooleanField(default=False),
        ),
    ]
