# Generated by Django 6.0.5 on 2026-08-14 12:30

import jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0011_progeolocation_flip_x_progeolocation_flip_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeoalarm',
            name='max_values',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
