# Generated by Django 6.0.5 on 2026-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0012_progeoalarm_max_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeoalarm',
            name='rain_amount',
            field=models.FloatField(blank=True, help_text='Precipitation in mm', null=True),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='rain_duration',
            field=models.FloatField(blank=True, help_text='Hours of rain found', null=True),
        ),
        migrations.AddField(
            model_name='progeoalarm',
            name='rain_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
