# Generated by Django 6.0.5 on 2026-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0013_progeoalarm_rain_amount_progeoalarm_rain_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeoalarm',
            name='rain_checked',
            field=models.BooleanField(blank=True, default=False, help_text='Whether rain check has been performed for this alarm'),
        ),
    ]
