# Generated by Django 6.0.5 on 2026-08-23 15:55

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0014_progeoalarm_rain_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeoalarm',
            name='sensor_max_values',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
