# Generated by Django 6.0.5 on 2026-08-23 21:25

import django.db.models.deletion
import django.db.models.manager
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0015_progeoalarm_sensor_max_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('active_count', models.IntegerField(default=0)),
                ('normalized_count', models.IntegerField(default=0)),
                ('acknowledged_count', models.IntegerField(default=0)),
                ('stoppage_count', models.IntegerField(default=0)),
                ('avg_duration_seconds', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('peak_sensor_id', models.IntegerField(blank=True, null=True)),
                ('max_value_at', models.DateTimeField(blank=True, null=True)),
                ('locations', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('sensors', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('hourly', jsonfield.fields.JSONField(blank=True, default=list)),
                ('top_alarms', jsonfield.fields.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progeo.account')),
            ],
            options={
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('account', 'date')},
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
