# Generated by Django 6.0.5 on 2026-08-24 11:10

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0016_alarmdailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmdailyreport',
            name='dead_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alarmdailyreport',
            name='disconnected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alarmdailyreport',
            name='online_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alarmdailyreport',
            name='projects',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
