# Generated by Django 6.0.5 on 2026-08-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0017_alarmdailyreport_dead_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='progeo.progeolocation'),
        ),
        migrations.AddField(
            model_name='email',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
