# Generated by Django 6.0.5 on 2026-09-01 23:24

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0019_progeoalarm_rain_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolocation',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='progeo.progeolocation'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='flip_x',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use ProgeoLageplan instead'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='flip_y',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use ProgeoLageplan instead'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='lageplan',
            field=models.FileField(blank=True, help_text='DEPRECATED: Use ProgeoLageplan instead', max_length=255, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='offset_latitude',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use ProgeoLageplan instead', null=True),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='offset_longitude',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use ProgeoLageplan instead', null=True),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='offset_x',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Use ProgeoLageplan instead', null=True),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='offset_y',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Use ProgeoLageplan instead', null=True),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='scale_x',
            field=models.FloatField(blank=True, default=1, help_text='DEPRECATED: Use ProgeoLageplan instead'),
        ),
        migrations.AlterField(
            model_name='progeolocation',
            name='scale_y',
            field=models.FloatField(blank=True, default=1, help_text='DEPRECATED: Use ProgeoLageplan instead'),
        ),
        migrations.CreateModel(
            name='ProgeoLageplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('lageplan', models.FileField(blank=True, max_length=255, null=True, upload_to='media/uploads')),
                ('name', models.CharField(blank=True, help_text='Optional name/version of this lageplan', max_length=255, null=True)),
                ('offset_x', models.IntegerField(blank=True, help_text='X offset in pixels', null=True)),
                ('offset_y', models.IntegerField(blank=True, help_text='Y offset in pixels', null=True)),
                ('scale_x', models.FloatField(blank=True, default=1, help_text='Scale factor for X axis')),
                ('scale_y', models.FloatField(blank=True, default=1, help_text='Scale factor for Y axis')),
                ('flip_x', models.BooleanField(default=False, help_text='Flip/mirror horizontally')),
                ('flip_y', models.BooleanField(default=False, help_text='Flip/mirror vertically')),
                ('offset_latitude', models.FloatField(blank=True, help_text='Latitude offset for georeferencing', null=True)),
                ('offset_longitude', models.FloatField(blank=True, help_text='Longitude offset for georeferencing', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the active/current lageplan')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lageplans', to='progeo.progeolocation')),
            ],
            options={
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
