# Generated by Django 6.0.5 on 2026-09-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0020_progeolocation_parent_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progeolocation',
            name='flip_x',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='flip_y',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='lageplan',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='offset_latitude',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='offset_longitude',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='offset_x',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='offset_y',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='scale_x',
        ),
        migrations.RemoveField(
            model_name='progeolocation',
            name='scale_y',
        ),
    ]
