# Generated by Django 6.0.5 on 2026-09-02 12:16

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0021_remove_progeolocation_flip_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'smartex'), (2, 'geologger'), (3, 'DFH'), (4, 'Development'), (5, 'Versuchsprojekte'), (99, 'Sonstige')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='progeomeasurepoint',
            name='lageplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lageplaene', to='progeo.progeolageplan'),
        ),
        migrations.CreateModel(
            name='ProgeoAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('transport', models.IntegerField(blank=True, choices=[(0, 'Silent'), (1, 'Email'), (2, 'Sms'), (4, 'Email And Sms')], null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Silent'), (1, 'Alarm'), (2, 'Timeout'), (4, 'News')], null=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='progeo.progeolocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(models.Model, object),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
