# Generated by Django 6.0.5 on 2026-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0025_create_module_permission_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolocation',
            name='pe_geschaltet',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='progeoalarm',
            name='status',
            field=models.IntegerField(choices=[(0, 'neu'), (1, 'quittiert'), (2, 'stoerung'), (3, 'geloest')], default=0),
        ),
    ]
