# Generated by Django 6.0.5 on 2026-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0026_progeolocation_pe_geschaltet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_distance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_integration_depth',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_m_status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_timeout',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='alarm_umfeld',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progeolocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
