# Generated by Django 6.0.5 on 2026-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0027_progeolocation_alarm_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeomeasurepoint',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
