# Generated by Django 6.0.5 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0028_progeomeasurepoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolocation',
            name='airtable_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
