# Generated by Django 6.0.5 on 2026-10-05 18:56

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0029_progeolocation_airtable_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=64)),
                ('sender', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('batch_id', models.CharField(blank=True, max_length=64, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='progeo.progeolocation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
