# Generated by Django 6.0.5 on 2026-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progeo', '0030_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='progeolageplan',
            name='meters_per_pixel',
            field=models.FloatField(blank=True, help_text='Meters per image pixel', null=True),
        ),
        migrations.AddField(
            model_name='progeolageplan',
            name='reference_x',
            field=models.FloatField(blank=True, help_text='Reference point x (image pixels)', null=True),
        ),
        migrations.AddField(
            model_name='progeolageplan',
            name='reference_y',
            field=models.FloatField(blank=True, help_text='Reference point y (image pixels)', null=True),
        ),
    ]
